# Generated by Django 5.1.15 on 2026-08-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0012_add_devto_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_target_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
