# Generated by Django 5.1.15 on 2026-08-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0013_socialaccount_webhook_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='webhooks_active',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
