# Generated by Django 5.1.15 on 2026-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0015_backfill_threads_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_error_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_needs_reconnect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='webhook_retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
