# Generated by Django 5.1.15 on 2026-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0017_seed_missing_analytics_platform_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='missing_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
