# Generated by Django 5.1.15 on 2026-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_accounts", "0018_socialaccount_missing_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="inbox_last_deep_sweep_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="inbox_last_polled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
