# Generated by Django 5.1.15 on 2026-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_set_site_brightbean"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="review_banner_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
