# Generated by Django 5.1.15 on 2026-08-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0019_merge_20260630_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpost',
            name='first_comment_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='first_comment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='first_comment_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='first_comment_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformpost',
            name='first_comment_status',
            field=models.CharField(choices=[('none', 'Not requested'), ('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], db_index=True, default='none', max_length=10),
        ),
    ]
